version: '3.5'
services:
  jeager_server:
    container_name: 'jeager_server'
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "80:16686"
    networks:
      - jeager-tracing
  vertex_ws:
    container_name: 'vertex_ws'
    build: .
    ports:
      - "9009:8080"
    networks:
      - jeager-tracing
    depends_on:
      - jeager_server
  dev_db:
    container_name: 'dev_db'
    image: 'postgres'
    environment:
      POSTGRES_DB: 'dev_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./infrastructure/1-dev_db.sql:/docker-entrypoint-initdb.d/1-dev_db.sql
    networks:
      - jeager-tracing
networks:
  jeager-tracing: